blogicum/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'),
    path(
        'posts/<int:post_id>/',
        views.post_detail,
        name='post_detail'
    ),
    path(
        'category/<slug:category_slug>/',
        views.category_posts,
        name='category_posts'
    ),
    path(
        'posts/create/',
        views.post_edit,
        name='create_post'
    ),
    path(
        'posts/<int:post_id>/edit/',
        views.post_edit,
        name='edit_post'
    ),
    path(
        'posts/<int:post_id>/delete/',
        views.post_delete,
        name='delete_post'
    ),
    path(
        'profile/<slug:username>/',
        views.Profile.as_view(),
        name='profile'
    ),
    path(
        'profile/<slug:username>/edit/',
        views.edit_profile,
        name='edit_profile'
    ),
    path(
        'create_shelf',
        views.create_shelf,
        name='create_shelf'
    ),
    path(
        'create_author',
        views.create_author,
        name='create_author'
    )
]

blogicum/blogicum/urls.py
from django.contrib import admin
from django.views.generic.edit import CreateView
from django.urls import include, path, reverse_lazy
from blog.forms import UserForm
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('pages/', include('pages.urls')),
    path('admin/', admin.site.urls),
    path(
        'auth/registration/',
        CreateView.as_view(
            template_name='registration/registration_form.html',
            form_class=UserForm,
            success_url=reverse_lazy('blog:index'),
        ),
        name='registration',
    ),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('blog.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'pages.views.page_not_found'
handler500 = 'pages.views.page_internal_server_error'

blogicum/blog/models.py
# Create your models here.
from django.db import models


class Author(models.Model):
    name = models.CharField(max_length=256, verbose_name="Имя")
    def __str__(self):
        return self.name

class BaseBlog(models.Model):
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name="Добавлено"
    )

    class Meta:
        abstract = True


class Shelf(BaseBlog):
    title = models.CharField(max_length=256, verbose_name="Название")
    description = models.TextField(verbose_name="Описание")
    slug = models.SlugField(unique=True,
                            verbose_name="Идентификатор",
                            help_text="Идентификатор страницы для URL; "
                                      "разрешены символы латиницы, "
                                      "цифры, дефис и подчёркивание."
                            )
    def __str__(self):
        return self.title


    class Meta:
        verbose_name = 'полка'
        verbose_name_plural = 'Полки'


class Book(BaseBlog):
    title = models.CharField(max_length=256, verbose_name="Заголовок")
    text = models.TextField(verbose_name="Текст", )
    price = models.DecimalField(max_digits=10, decimal_places=2)
    amount = models.IntegerField(verbose_name="Остаток")
    author = models.ForeignKey(
        Author,
        on_delete=models.CASCADE,
        verbose_name="Автор книги",
        related_name="posts"
    )
    shelf = models.ForeignKey(
        Shelf,
        on_delete=models.SET_NULL,
        verbose_name="Полка",
        null=True
    )
    image = models.ImageField(
        upload_to="media/",
        null=True,
        verbose_name="Обложка",
        blank=True,
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'книга'
        verbose_name_plural = 'Книги'

blogicum/blog/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django import forms
from blog.models import Book, Author, Shelf

User = get_user_model()


class UserForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ['username', 'email', 'first_name',
                  'last_name', 'password1', 'password2']


class UserEditForm(forms.ModelForm):
    class Meta(UserCreationForm.Meta):
        model = Author
        fields = ['name']


class PostForm(forms.ModelForm):
    class Meta:
        fields = "__all__"
        widgets = {
            'text': forms.Textarea
        }
        model = Book


class ShelfForm(forms.ModelForm):
    class Meta(UserCreationForm.Meta):
        model = Shelf
        fields = "__all__"

blogicum/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Book, Shelf, Author
from django.core.paginator import Paginator
from django.views import View
from blog.forms import UserEditForm, PostForm, ShelfForm
from django.contrib.auth.decorators import login_required


# Create your views here.
def index(request):
    books = Book.objects.filter(
        amount__gte=1,
    )
    paginator = Paginator(books, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'blog/index.html', {'page_obj': page_obj})


def create_edit(request, book_id=None):
    book = get_object_or_404(
        Book,
        pk=book_id,
        amount__gte=1,
    )
    return render(request, 'blog/detail.html', {'post': book})


def post_detail(request, post_id):
    book = get_object_or_404(
        Book,
        pk=post_id,
    )

    if request.user != book.author:
        book = get_object_or_404(
            Book,
            pk=post_id,
            amount__gte=1,
        )
    return render(
        request,
        'blog/detail.html',
        {
            'post': book,
        }
    )


def category_posts(request, category_slug):
    category = get_object_or_404(
        Shelf,
        slug=category_slug,
    )
    books = Book.objects.filter(
        amount__gte=1,
        shelf=category
    )
    paginator = Paginator(books, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(
        request,
        'blog/category.html',
        {
            'page_obj': page_obj,
            'category': category
        }
    )


class Profile(View):
    template = 'blog/profile.html'

    def get(self, request, **kwargs):
        name = kwargs['username']
        profile = get_object_or_404(Author, name=name)
        books = Book.objects.filter(author=profile)
        paginator = Paginator(books, 10)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        contex = {
            "profile": profile,
            'page_obj': page_obj
        }
        return render(request, self.template, contex)


@login_required
def edit_profile(request, username):
    if request.method == "POST":
        form = UserEditForm(request.POST)
        if form.is_valid():
            user = Author.objects.get(pk=request.user.pk)
            user.name = form.cleaned_data["name"]
            user.save()
        context = {
            "form": form
        }
        return render(request, 'blog/user.html', context)
    form = UserEditForm(instance=get_object_or_404(Author, name=username))
    context = {
        "form": form
    }
    return render(request, 'blog/user.html', context)


@login_required
def post_edit(request, post_id=None):
    form = PostForm()
    if request.method == 'POST':
        if post_id is not None:
            form = PostForm(request.POST, request.FILES)
            instance = get_object_or_404(Book, pk=post_id)
            if form.is_valid():
                book = get_object_or_404(
                    Book,
                    pk=post_id
                )
                book.text = form.cleaned_data["text"]
                book.title = form.cleaned_data["title"]
                book.shelf = form.cleaned_data["shelf"]
                book.author = form.cleaned_data["author"]
                book.image = form.cleaned_data["image"]
                book.save()
                return redirect("blog:post_detail", post_id=post_id)
        else:
            form = PostForm(request.POST, request.FILES)
            if form.is_valid():
                book = form.save()
                return redirect("blog:profile", username=book.author.name)
    else:
        if post_id is not None:
            instance = get_object_or_404(Book, pk=post_id)
            form = PostForm(instance=instance)
    context = {'form': form}
    return render(request, 'blog/create.html', context)


def post_delete(request, post_id):
    book = get_object_or_404(Book, pk=post_id)
    instance = get_object_or_404(Book, id=post_id)
    form = PostForm(instance=book)
    context = {'form': form}
    if request.method == 'POST':
        instance.delete()
        return redirect('blog:index')
    return render(request, 'blog/create.html', context)


def create_shelf(request):
    if request.method == 'POST':
        form = ShelfForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("blog:index")
    form = ShelfForm()
    context = {"form": form}
    return render(request, 'blog/create.html', context)


def create_author(request):
    if request.method == 'POST':
        form = UserEditForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("blog:index")
    form = UserEditForm()
    context = {"form": form}
    return render(request, 'blog/create.html', context)

blogicum/templates/blog/category.html
{% extends "base.html" %}
{% block title %}
  Книги на полке {{ category.title }}
{% endblock %}
{% block content %}
  <h1 class="text-center">Книги на полке - {{ category.title }}</h1>
  <p class="col-6 offset-3 mb-5 lead text-center">{{ category.description }}</p>
  {% for post in page_obj %}
    <article class="mb-5">  
      {% include "includes/post_card.html" %}
    </article>   
  {% endfor %}
  {% include "includes/paginator.html" %}
{% endblock %}

blogicum/templates/blog/comment.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block title %}
  {% if '/edit_comment/' in request.path %}
    Редактирование комментария
  {% else %}
    Удаление комментария
  {% endif %}
{% endblock %}
{% block content %}
  {% if user.is_authenticated %}
    <div class="col d-flex justify-content-center">
      <div class="card" style="width: 40rem;">
        <div class="card-header">
          {% if '/edit_comment/' in request.path %}
            Редактирование комментария
          {% else %}
            Удаление комментария
          {% endif %}
        </div>
        <div class="card-body">
          <form method="post"
            {% if '/edit_comment/' in request.path %}
              action="{% url 'blog:edit_comment' comment.post_id comment.id %}"
            {% endif %}>
            {% csrf_token %}
            {% if not '/delete_comment/' in request.path %}
              {% bootstrap_form form %}
            {% else %}
              <p>{{ comment.text }}</p>
            {% endif %}
            {% bootstrap_button button_type="submit" content="Отправить" %}
          </form>
        </div>
      </div>
    </div>
  {% endif %}
{% endblock %}

blogicum/templates/blog/create.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block title %}
  {% if '/edit/' in request.path %}
    Редактирование книги
  {% elif "/delete/" in request.path %}
    Удаление книги
  {% else %}
    Добавление книги
  {% endif %}
{% endblock %}
{% block content %}
  <div class="col d-flex justify-content-center">
    <div class="card" style="width: 40rem;">
      <div class="card-header">
        {% if '/edit/' in request.path %}
          Редактирование книги
        {% elif '/delete/' in request.path %}
          Удаление книги
        {% else %}
          Страница добавления
        {% endif %}
      </div>
      <div class="card-body">
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {% if not '/delete/' in request.path %}
            {% bootstrap_form form %}
          {% else %}
            <article>
              {% if form.instance.image %}
                <a href="{{ form.instance.image.url }}" target="_blank">
                  <img class="border-3 rounded img-fluid img-thumbnail mb-2" src="{{ form.instance.image.url }}">
                </a>
              {% endif %}
              <p>{{ form.instance.pub_date|date:"d E Y" }} | {% if form.instance.location and form.instance.location.is_published %}{{ form.instance.location.name }}{% else %}Планета Земля{% endif %}<br>
              <h3>{{ form.instance.title }}</h3>
              <p>{{ form.instance.text|linebreaksbr }}</p>
            </article>
          {% endif %}
          {% bootstrap_button button_type="submit" content="Отправить" %}
        </form>
      </div>
    </div>
  </div>
{% endblock %}

blogicum/templates/blog/detail.html
{% extends "base.html" %}
{% block title %}
{% endblock %}
{% block content %}
  <div class="col d-flex justify-content-center">
    <div class="card" style="width: 40rem;">
      <div class="card-body">
        {% if post.image %}
          <a href="{{ post.image.url }}" target="_blank">
            <img class="border-3 rounded img-fluid img-thumbnail mb-2 mx-auto d-block" src="{{ post.image.url }}">
          </a>
        {% endif %}
        <h5 class="card-title">{{ post.title }}</h5>
        <h6>Цена: {{ post.price }}</h6>
        <h6 >Осталось: {{ post.amount }}</h6>
        <h6 class="card-subtitle mb-2 text-muted">
          <small>
            От автора <a class="text-muted" href="{% url 'blog:profile' post.author.name %}">@{{ post.author.name }}</a>
            на полке {% include "includes/category_link.html" %}
          </small>
        </h6>
        <p class="card-text">{{ post.text|linebreaksbr }}</p>
          <div class="mb-2">
            <a class="btn btn-sm text-muted" href="{% url 'blog:edit_post' post.id %}" role="button">
              Отредактировать
            </a>
            <a class="btn btn-sm text-muted" href="{% url 'blog:delete_post' post.id %}" role="button">
              Удалить
            </a>
          </div>
      </div>
    </div>
  </div>
{% endblock %}

blogicum/templates/blog/index.html
{% extends "base.html" %}
{% block title %}
  Лента записей
{% endblock %}
{% block content %}
  {% for post in page_obj %}
    <article class="mb-5">
      {% include "includes/post_card.html" %}
    </article>
  {% endfor %}
  {% include "includes/paginator.html" %}
{% endblock %}

blogicum/templates/blog/profile.html
{% extends "base.html" %}
{% block title %}
  Страница пользователя {{ profile.username }}
{% endblock %}
{% block content %}
  <h1 class="mb-5 text-center ">Страница пользователя {{ profile.name }}</h1>
  <small>
    <ul class="list-group list-group-horizontal justify-content-center mb-3">
      <li class="list-group-item text-muted">Имя пользователя: {% if profile.get_full_name %}{{ profile.get_full_name }}{% else %}не указано{% endif %}</li>
      <li class="list-group-item text-muted">Регистрация: {{ profile.date_joined }}</li>
      <li class="list-group-item text-muted">Роль: {% if profile.is_staff %}Админ{% else %}Пользователь{% endif %}</li>
    </ul>
    <ul class="list-group list-group-horizontal justify-content-center">
      <a class="btn btn-sm text-muted" href="{% url 'blog:edit_profile' profile.name %}">Редактировать автора</a>
    </ul>
  </small>
  <br>
  <h3 class="mb-5 text-center">Публикации пользователя</h3>
  {% for post in page_obj %}
    <article class="mb-5">
      {% include "includes/post_card.html" %}
    </article>
  {% endfor %}
  {% include "includes/paginator.html" %}
{% endblock %}

blogicum/templates/blog/user.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block title %}
  Редактирование профиля
{% endblock %}
{% block content %}
  <div class="col d-flex justify-content-center">
    <div class="card" style="width: 40rem;">
      <div class="card-header">
        Редактирование профиля - {{ author.name }}
      </div>
      <div class="card-body">
        <form method="post">
          {% csrf_token %}
          {% bootstrap_form form %}
          {% bootstrap_button button_type="submit" content="Отправить" %}
        </form>
      </div>
    </div>
  </div>
{% endblock %}